### ISSUE TITLE
Comfyui has already installed the comfyui art venture plugin, but it actually shows that the node was not found. How should we solve this problem

### ISSUE THREAD

**Issue by zqtop** [sipherxyz/comfyui-art-venture#29]
When loading the graph, the following node types were not found:
comfyui-art-venture[ 🔗](https://github.com/sipherxyz/comfyui-art-venture)
Nodes that have failed to load will show as red on the graph.

**Comment by zqtop** [comment]
![Uploading 1.png…]()

**Comment by tungnguyensipher** [comment]
Can you post logs from boot console.

**Comment by Alera156** [comment]
> Can you post logs from boot console.

I have the same issue. 
Tried to uninstall and reinstall, I installed the two packages in Python site-packages.

<img width="456" alt="2024-04-23 15_52_01-ComfyUI – Mozilla Firefox" src="https://github.com/sipherxyz/comfyui-art-venture/assets/121126737/8f52d656-935c-4844-93b3-3ece025908da">

**Comment by Alera156** [comment]
> When loading the graph, the following node types were not found: comfyui-art-venture[ 🔗](https://github.com/sipherxyz/comfyui-art-venture) Nodes that have failed to load will show as red on the graph.

I had the same issue.
I found out that I need to run [pip install omegaconf] in the Python folder, located, in my case, in: 

C\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages

and NOT in:
ComfyUI_windows_portable\python_embeded\Lib\site-packages.

**Comment by oO0** [comment]
This bug related to last 2 week ComfyUI update. Versions of May 2024 works good

Cannot import ...\ComfyUI\ComfyUI\custom_nodes\ComfyUI-ADMotionDirector module for custom nodes: cannot import name 'EDMDPMSolverMultistepScheduler' from 'diffusers.schedulers' (...\ComfyUI\python_embeded\Lib\site-packages\diffusers\schedulers\__init__.py)
Adding ...\ComfyUI\ComfyUI\custom_nodes to sys.path
Traceback (most recent call last):
  File "...\ComfyUI\ComfyUI\nodes.py", line 1890, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "...\ComfyUI\ComfyUI\custom_nodes\comfyui-art-venture\__init__.py", line 13, in <module>
    from .modules.nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "...\ComfyUI\ComfyUI\custom_nodes\comfyui-art-venture\modules\nodes.py", line 18, in <module>
    from .utility_nodes import (
  File "...\ComfyUI\ComfyUI\custom_nodes\comfyui-art-venture\modules\utility_nodes.py", line 15, in <module>
    from comfy_extras.nodes_upscale_model import ImageUpscaleWithModel
  File "...\ComfyUI\ComfyUI\comfy_extras\nodes_upscale_model.py", line 3, in <module>
    from spandrel import ModelLoader, ImageModelDescriptor
ModuleNotFoundError: No module named 'spandrel'

Cannot import ...\ComfyUI\ComfyUI\custom_nodes\comfyui-art-venture module for custom nodes: No module named 'spandrel'

**Comment by yovsac** [comment]
Having the same issue. The nodes show up red. 

Here is my log.... Any ideas?

![Screenshot 2024-10-29 122903](https://github.com/user-attachments/assets/63530b7f-d338-4de5-a855-420ae19216c2)

**Comment by Fragmatico** [comment]
Looks like the same error code here with zipimporter.

---
Error message occurred while importing the 'ComfyUI ArtVenture' module.

Traceback (most recent call last):
  File "E:\ComfyUI\ComfyUI\nodes.py", line 2108, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "E:\ComfyUI\ComfyUI\custom_nodes\comfyui-art-venture\__init__.py", line 13, in <module>
    from .modules.nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "E:\ComfyUI\ComfyUI\custom_nodes\comfyui-art-venture\modules\nodes.py", line 12, in <module>
    from .utility_nodes import (
  File "E:\ComfyUI\ComfyUI\custom_nodes\comfyui-art-venture\modules\utility_nodes.py", line 17, in <module>
    from .utils import pil2tensor, tensor2pil, ensure_package, get_dict_attribute
  File "E:\ComfyUI\ComfyUI\custom_nodes\comfyui-art-venture\modules\utils.py", line 9, in <module>
    import pkg_resources
  File "E:\ComfyUI\python_embeded\Lib\site-packages\pkg_resources\__init__.py", line 2191, in <module>
    register_finder(pkgutil.ImpImporter, find_on_path)
                    ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
---

Any help on this please? I really like using some of the nodes. Until tonight. Just stopped loading.

Thanks.
