### ISSUE TITLE
(import failed) TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

### ISSUE THREAD

**Issue by HansonChan** [sipherxyz/comfyui-art-venture#38]
on mac m2
log as blow:

 Traceback (most recent call last):
  File "/Users/Shuai/AI/ComfyUI/nodes.py", line 1906, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/Shuai/AI/ComfyUI/custom_nodes/comfyui-art-venture/__init__.py", line 13, in <module>
    from .modules.nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/Users/Shuai/AI/ComfyUI/custom_nodes/comfyui-art-venture/modules/nodes.py", line 26, in <module>
    from .interrogate import (
  File "/Users/Shuai/AI/ComfyUI/custom_nodes/comfyui-art-venture/modules/interrogate/__init__.py", line 1, in <module>
    from .blip_node import BlipLoader, BlipCaption
  File "/Users/Shuai/AI/ComfyUI/custom_nodes/comfyui-art-venture/modules/interrogate/blip_node.py", line 10, in <module>
    from ..model_utils import download_model
  File "/Users/Shuai/AI/ComfyUI/custom_nodes/comfyui-art-venture/modules/model_utils.py", line 40, in <module>
    file_name: str | None = None,
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

**Comment by HansonChan** [comment]
due to python version

**Comment by zeyad11ZXC** [comment]
what about python version 
need newer verison or older ?
