### ISSUE TITLE
(IMPORT FAILED) ModuleNotFoundError: No module named 'segment_anything'

### ISSUE THREAD

**Issue by esqanor** [sipherxyz/comfyui-art-venture#4]
This error appears when trying to install. I'm new to comfyui, but I've tried everything I can find on the internet, nothing helps. 

`Traceback (most recent call last):
  File "C:\SD\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1800, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\SD\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture\__init__.py", line 10, in <module>
    from .modules.nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\SD\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture\modules\nodes.py", line 54, in <module>
    from .inpaint import (
  File "C:\SD\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture\modules\inpaint\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\SD\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture\modules\inpaint\nodes.py", line 7, in <module>
    from .sam.nodes import SAMLoader, GetSAMEmbedding, SAMEmbeddingToImage
  File "C:\SD\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture\modules\inpaint\sam\nodes.py", line 5, in <module>
    from segment_anything import SamPredictor, sam_model_registry
ModuleNotFoundError: No module named 'segment_anything'

Cannot import C:\SD\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture module for custom nodes: No module named 'segment_anything'`

**Comment by patrickgalbraith** [comment]
I had to manually install the below packages to get it to run (use the below if you're using the portable install):

```
.\python_embeded\python.exe -s -m pip install segment_anything
.\python_embeded\python.exe -s -m pip install omegaconf
```

**Comment by maomao123-pcu** [comment]
<img width="803" alt="截屏2023-12-24 22 32 34" src="https://github.com/sipherxyz/comfyui-art-venture/assets/126594794/936c6257-a93a-427e-b640-87c8c6f85487">
I have the same error as you, I have installed the dependencies but still not working，Does it have an answer?

**Comment by Emirufio** [comment]
> I had to manually install the below packages to get it to run (use the below if you're using the portable install):
> 
> ```
> .\python_embeded\python.exe -s -m pip install segment_anything
> .\python_embeded\python.exe -s -m pip install omegaconf
> ```

Hi can you explain me how to install manually those package
I am a newbie
Regards

**Comment by unique15** [comment]
> I had to manually install the below packages to get it to run (use the below if you're using the portable install):
> 
> ```
> .\python_embeded\python.exe -s -m pip install segment_anything
> .\python_embeded\python.exe -s -m pip install omegaconf
> ```

Do you have any command to install it on runpod machine?

**Comment by jordanl61** [comment]
This worked! Thanks @patrickgalbraith

**Comment by gurprxet** [comment]
> > I had to manually install the below packages to get it to run (use the below if you're using the portable install):
> > ```
> > .\python_embeded\python.exe -s -m pip install segment_anything
> > .\python_embeded\python.exe -s -m pip install omegaconf
> > ```
> 
> Hi can you explain me how to install manually those package I am a newbie Regards

Maybe you already had resolved the issue but here if not resolved yet,

go to - comfy_ui/custom_nodes/
   open cmd prompt inside the custom node folder,
     use command > git clone (url of your custom_node from github)
        it will install the node in that folder
            launch comfyui (restart if already running + refresh browser)
               if still error appears use manager > custom node manager > find installed nodes > click try fix > restart + refresh browser
                   i hope it will fix the issue, worked for me.
