### ISSUE TITLE
List index out of range error

### ISSUE THREAD

**Issue by ruichang555** [sipherxyz/comfyui-art-venture#45]
I am following this YouTube tutorial (https://www.youtube.com/watch?v=g74Cq9Ip2ik
). At about 58:29 of the video, I installed art vent controlnet preprocessor. At first, the preprocessor dropdown list only contains tile and none pre-processor. I then installed comfyui_controlnet_aux, then I am able to see the dropdown list of pre-processors (I think the ip-adaptor is still missing). 

Anyway, when I try to run my workflow, I got the following error in the boot console. 

I am not sure what's wrong?

Thanks!

# ComfyUI Error Report
## Error Details
- **Node Type:** AV_ControlNetPreprocessor
- **Exception Type:** IndexError
- **Exception Message:** list index out of range
## Stack Trace
```
  File "C:\Users\User\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\User\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\User\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "C:\Users\User\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\User\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture\modules\controlnet\__init__.py", line 136, in detect_controlnet
    image = apply_preprocessor(image, preprocessor, resolution=resolution)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\User\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture\modules\controlnet\__init__.py", line 43, in apply_preprocessor
    preprocessor_args.update({key: default_args[i + len(required_args)] for i, key in enumerate(optional_args)})
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\User\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture\modules\controlnet\__init__.py", line 43, in <dictcomp>
    preprocessor_args.update({key: default_args[i + len(required_args)] for i, key in enumerate(optional_args)})
                                   ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^

```
## System Information
- **ComfyUI Version:** v0.2.2-18-g54fca4a
- **Arguments:** ComfyUI\main.py --windows-standalone-build
- **OS:** nt
- **Python Version:** 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.4.1+cu124
## Devices

- **Name:** cuda:0 NVIDIA RTX A6000 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 51526500352
  - **VRAM Free:** 49854545920
  - **Torch VRAM Total:** 0
  - **Torch VRAM Free:** 0

## Logs
```
2024-09-10 14:10:55,063 - root - INFO - Total VRAM 49140 MB, total RAM 524129 MB
2024-09-10 14:10:55,063 - root - INFO - pytorch version: 2.4.1+cu124
2024-09-10 14:10:55,064 - root - INFO - Set vram state to: NORMAL_VRAM
2024-09-10 14:10:55,064 - root - INFO - Device: cuda:0 NVIDIA RTX A6000 : cudaMallocAsync
2024-09-10 14:10:56,727 - root - INFO - Using pytorch cross attention
2024-09-10 14:10:58,606 - root - INFO - [Prompt Server] web root: C:\Users\User\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\web
2024-09-10 14:11:02,025 - root - INFO - 
Import times for custom nodes:
2024-09-10 14:11:02,025 - root - INFO -    0.0 seconds: C:\Users\User\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
2024-09-10 14:11:02,025 - root - INFO -    0.0 seconds: C:\Users\User\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg-image-picker
2024-09-10 14:11:02,025 - root - INFO -    0.0 seconds: C:\Users\User\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
2024-09-10 14:11:02,025 - root - INFO -    0.0 seconds: C:\Users\User\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
2024-09-10 14:11:02,025 - root - INFO -    0.4 seconds: C:\Users\User\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
2024-09-10 14:11:02,025 - root - INFO -    2.3 seconds: C:\Users\User\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture
2024-09-10 14:11:02,026 - root - INFO - 
2024-09-10 14:11:02,032 - root - INFO - Starting server

2024-09-10 14:11:02,032 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-09-10 14:25:27,504 - root - INFO - got prompt
2024-09-10 14:25:27,964 - root - ERROR - !!! Exception during processing !!! list index out of range
2024-09-10 14:25:27,966 - root - ERROR - Traceback (most recent call last):
  File "C:\Users\User\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\User\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture\modules\controlnet\__init__.py", line 136, in detect_controlnet
    image = apply_preprocessor(image, preprocessor, resolution=resolution)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture\modules\controlnet\__init__.py", line 43, in apply_preprocessor
    preprocessor_args.update({key: default_args[i + len(required_args)] for i, key in enumerate(optional_args)})
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture\modules\controlnet\__init__.py", line 43, in <dictcomp>
    preprocessor_args.update({key: default_args[i + len(required_args)] for i, key in enumerate(optional_args)})
                                   ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range

2024-09-10 14:25:27,968 - root - INFO - Prompt executed in 0.46 seconds
2024-09-10 14:27:52,726 - root - INFO - got prompt
2024-09-10 14:27:52,753 - root - ERROR - !!! Exception during processing !!! list index out of range
2024-09-10 14:27:52,754 - root - ERROR - Traceback (most recent call last):
  File "C:\Users\User\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\User\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture\modules\controlnet\__init__.py", line 136, in detect_controlnet
    image = apply_preprocessor(image, preprocessor, resolution=resolution)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture\modules\controlnet\__init__.py", line 43, in apply_preprocessor
    preprocessor_args.update({key: default_args[i + len(required_args)] for i, key in enumerate(optional_args)})
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture\modules\controlnet\__init__.py", line 43, in <dictcomp>
    preprocessor_args.update({key: default_args[i + len(required_args)] for i, key in enumerate(optional_args)})
                                   ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range

2024-09-10 14:27:52,755 - root - INFO - Prompt executed in 0.02 seconds
2024-09-10 14:28:05,832 - root - INFO - got prompt
2024-09-10 14:28:05,853 - root - ERROR - !!! Exception during processing !!! list index out of range
2024-09-10 14:28:05,854 - root - ERROR - Traceback (most recent call last):
  File "C:\Users\User\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\User\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture\modules\controlnet\__init__.py", line 136, in detect_controlnet
    image = apply_preprocessor(image, preprocessor, resolution=resolution)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture\modules\controlnet\__init__.py", line 43, in apply_preprocessor
    preprocessor_args.update({key: default_args[i + len(required_args)] for i, key in enumerate(optional_args)})
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture\modules\controlnet\__init__.py", line 43, in <dictcomp>
    preprocessor_args.update({key: default_args[i + len(required_args)] for i, key in enumerate(optional_args)})
                                   ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range

2024-09-10 14:28:05,855 - root - INFO - Prompt executed in 0.02 seconds
2024-09-10 14:43:52,166 - root - INFO - got prompt
2024-09-10 14:43:52,191 - root - ERROR - !!! Exception during processing !!! list index out of range
2024-09-10 14:43:52,191 - root - ERROR - Traceback (most recent call last):
  File "C:\Users\User\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\User\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture\modules\controlnet\__init__.py", line 136, in detect_controlnet
    image = apply_preprocessor(image, preprocessor, resolution=resolution)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture\modules\controlnet\__init__.py", line 43, in apply_preprocessor
    preprocessor_args.update({key: default_args[i + len(required_args)] for i, key in enumerate(optional_args)})
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture\modules\controlnet\__init__.py", line 43, in <dictcomp>
    preprocessor_args.update({key: default_args[i + len(required_args)] for i, key in enumerate(optional_args)})
                                   ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range

2024-09-10 14:43:52,194 - root - INFO - Prompt executed in 0.02 seconds
```

**Comment by ruichang555** [comment]
After a restart, the error message changed to the following about resolution.

# ComfyUI Error Report
## Error Details
- **Node Type:** AV_ControlNetPreprocessor
- **Exception Type:** ValueError
- **Exception Message:** 'resolution' is not in list
## Stack Trace
```
  File "C:\Users\User\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\User\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\User\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "C:\Users\User\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\User\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture\modules\controlnet\__init__.py", line 136, in detect_controlnet
    image = apply_preprocessor(image, preprocessor, resolution=resolution)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\User\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture\modules\controlnet\__init__.py", line 38, in apply_preprocessor
    resolution_idx = list(optional_args).index("resolution")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by Yaiol** [comment]
This error appears recently and seems to be linked with pose, openpose, dwpose.preprocessor only
A fast solution I used, is to replace the node "Controlnet Preprocessor" of art venture with "AIO Aux Preprocessor" node of https://github.com/Fannovel16/comfyui_controlnet_aux.

**Comment by JJonC1995** [comment]
Following as I am having identical issues. Actually from the same YouTube tutorial too!

**Comment by tungnguyensipher** [comment]
Please switch to node "AIO Aux Preprocessor" from [comfyui_controlnet_aux](https://github.com/Fannovel16/comfyui_controlnet_aux). This node is just a wrapper of comfyui_controlnet_aux.
