### ISSUE TITLE
LaMaInpaint Error : PytorchStreamReader failed locating file constants.pkl: file not found

### ISSUE THREAD

**Issue by poldos** [sipherxyz/comfyui-art-venture#50]
# ComfyUI Error Report
## Error Details
- **Node Type:** LaMaInpaint
- **Exception Type:** RuntimeError
- **Exception Message:** PytorchStreamReader failed locating file constants.pkl: file not found
## Stack Trace
```
  File "C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture\modules\inpaint\lama\__init__.py", line 75, in lama_inpaint
    model = load_model()
            ^^^^^^^^^^^^

  File "C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture\modules\inpaint\lama\__init__.py", line 43, in load_model
    lama = torch.jit.load(files[0], map_location="cpu")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\poldo\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\jit\_serialization.py", line 163, in load
    cpp_module = torch._C.import_ir_module(cu, os.fspath(f), map_location, _extra_files, _restore_shapes)  # type: ignore[call-arg]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```
## System Information
- **ComfyUI Version:** v0.2.4-12-g669d9e4
- **Arguments:** ComfyUI\main.py --windows-standalone-build
- **OS:** nt
- **Python Version:** 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.4.1+cu124
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 4070 Laptop GPU : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 8585216000
  - **VRAM Free:** 7398752256
  - **Torch VRAM Total:** 0
  - **Torch VRAM Free:** 0

## Logs
```
2024-10-28 17:48:10,292 - root - INFO - Total VRAM 8188 MB, total RAM 32386 MB
2024-10-28 17:48:10,293 - root - INFO - pytorch version: 2.4.1+cu124
2024-10-28 17:48:10,293 - root - INFO - Set vram state to: NORMAL_VRAM
2024-10-28 17:48:10,293 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4070 Laptop GPU : cudaMallocAsync
2024-10-28 17:48:11,455 - root - INFO - Using pytorch cross attention
2024-10-28 17:48:13,286 - root - INFO - [Prompt Server] web root: C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\web
2024-10-28 17:48:13,289 - root - INFO - Adding extra search path checkpoints C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\models/checkpoints/
2024-10-28 17:48:13,290 - root - INFO - Adding extra search path clip C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\models/clip/
2024-10-28 17:48:13,290 - root - INFO - Adding extra search path clip_vision C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\models/clip_vision/
2024-10-28 17:48:13,291 - root - INFO - Adding extra search path configs C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\models/configs/
2024-10-28 17:48:13,291 - root - INFO - Adding extra search path controlnet C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\models/controlnet/
2024-10-28 17:48:13,291 - root - INFO - Adding extra search path diffusion_models C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\models/diffusion_models/
2024-10-28 17:48:13,292 - root - INFO - Adding extra search path diffusion_models C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\models/unet/
2024-10-28 17:48:13,292 - root - INFO - Adding extra search path embeddings C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\models/embeddings/
2024-10-28 17:48:13,294 - root - INFO - Adding extra search path loras C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\models/loras/
2024-10-28 17:48:13,297 - root - INFO - Adding extra search path upscale_models C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\models/upscale_models/
2024-10-28 17:48:13,298 - root - INFO - Adding extra search path vae C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\models/vae/
2024-10-28 17:48:13,300 - root - INFO - Adding extra search path AnimateDiff D:\StableDiffusion\AnimateDiff/
2024-10-28 17:48:13,302 - root - INFO - Adding extra search path animatediff_models D:\StableDiffusion\animatediff_models/
2024-10-28 17:48:13,302 - root - INFO - Adding extra search path animatediff_motion_lora D:\StableDiffusion\animatediff_motion_lora/
2024-10-28 17:48:13,302 - root - INFO - Adding extra search path checkpoints D:\StableDiffusion\checkpoints/
2024-10-28 17:48:13,307 - root - INFO - Adding extra search path clip D:\StableDiffusion\clip/
2024-10-28 17:48:13,308 - root - INFO - Adding extra search path clip_vision D:\StableDiffusion\clip_vision/
2024-10-28 17:48:13,310 - root - INFO - Adding extra search path configs D:\StableDiffusion\configs/
2024-10-28 17:48:13,315 - root - INFO - Adding extra search path controlnet D:\StableDiffusion\controlnet/
2024-10-28 17:48:13,315 - root - INFO - Adding extra search path embeddings D:\StableDiffusion\embeddings/
2024-10-28 17:48:13,319 - root - INFO - Adding extra search path gligen D:\StableDiffusion\gligen/
2024-10-28 17:48:13,320 - root - INFO - Adding extra search path ipadapter D:\StableDiffusion\ipadapter/
2024-10-28 17:48:13,321 - root - INFO - Adding extra search path loras D:\StableDiffusion\loras/
2024-10-28 17:48:13,321 - root - INFO - Adding extra search path unet D:\StableDiffusion\unet/
2024-10-28 17:48:13,321 - root - INFO - Adding extra search path upscale_models D:\StableDiffusion\upscale_models/
2024-10-28 17:48:13,321 - root - INFO - Adding extra search path vae D:\StableDiffusion\vae/
2024-10-28 17:48:15,837 - ComfyUI-CogVideoXWrapper.custom_cogvideox_transformer_3d - INFO - sageattn not found, using sdpa
2024-10-28 17:48:15,890 - ComfyUI-CogVideoXWrapper.cogvideox_fun.transformer_3d - INFO - sageattn not found, using sdpa
2024-10-28 17:48:15,893 - ComfyUI-CogVideoXWrapper.cogvideox_fun.fun_pab_transformer_3d - INFO - sageattn not found, using sdpa
2024-10-28 17:48:16,434 - root - INFO - Total VRAM 8188 MB, total RAM 32386 MB
2024-10-28 17:48:16,434 - root - INFO - pytorch version: 2.4.1+cu124
2024-10-28 17:48:16,436 - root - INFO - Set vram state to: NORMAL_VRAM
2024-10-28 17:48:16,436 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4070 Laptop GPU : cudaMallocAsync
2024-10-28 17:48:20,094 - root - WARNING - Traceback (most recent call last):
  File "C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2006, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\poldo\\AI\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\HandRefiner\\__init__.py'

2024-10-28 17:48:20,094 - root - WARNING - Cannot import C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\HandRefiner module for custom nodes: [Errno 2] No such file or directory: 'C:\\Users\\poldo\\AI\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\HandRefiner\\__init__.py'
2024-10-28 17:48:21,849 - root - INFO - 
Import times for custom nodes:
2024-10-28 17:48:21,849 - root - INFO -    0.0 seconds: C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
2024-10-28 17:48:21,850 - root - INFO -    0.0 seconds: C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
2024-10-28 17:48:21,850 - root - INFO -    0.0 seconds: C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\sdxl_prompt_styler
2024-10-28 17:48:21,850 - root - INFO -    0.0 seconds: C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui
2024-10-28 17:48:21,851 - root - INFO -    0.0 seconds: C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
2024-10-28 17:48:21,851 - root - INFO -    0.0 seconds: C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
2024-10-28 17:48:21,851 - root - INFO -    0.0 seconds: C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\stability-ComfyUI-nodes
2024-10-28 17:48:21,852 - root - INFO -    0.0 seconds (IMPORT FAILED): C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\HandRefiner
2024-10-28 17:48:21,852 - root - INFO -    0.0 seconds: C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg-image-picker
2024-10-28 17:48:21,853 - root - INFO -    0.0 seconds: C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
2024-10-28 17:48:21,854 - root - INFO -    0.0 seconds: C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyMath
2024-10-28 17:48:21,854 - root - INFO -    0.0 seconds: C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-animatediff
2024-10-28 17:48:21,854 - root - INFO -    0.0 seconds: C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Florence2
2024-10-28 17:48:21,854 - root - INFO -    0.0 seconds: C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
2024-10-28 17:48:21,854 - root - INFO -    0.0 seconds: C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
2024-10-28 17:48:21,854 - root - INFO -    0.0 seconds: C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
2024-10-28 17:48:21,855 - root - INFO -    0.0 seconds: C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-FFmpeg
2024-10-28 17:48:21,855 - root - INFO -    0.0 seconds: C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
2024-10-28 17:48:21,855 - root - INFO -    0.0 seconds: C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
2024-10-28 17:48:21,855 - root - INFO -    0.0 seconds: C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
2024-10-28 17:48:21,855 - root - INFO -    0.0 seconds: C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
2024-10-28 17:48:21,856 - root - INFO -    0.1 seconds: C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_3dPoseEditor
2024-10-28 17:48:21,856 - root - INFO -    0.1 seconds: C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-ToSVG
2024-10-28 17:48:21,856 - root - INFO -    0.1 seconds: C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KJNodes
2024-10-28 17:48:21,856 - root - INFO -    0.3 seconds: C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
2024-10-28 17:48:21,857 - root - INFO -    0.4 seconds: C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools
2024-10-28 17:48:21,857 - root - INFO -    0.5 seconds: C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes
2024-10-28 17:48:21,857 - root - INFO -    0.6 seconds: C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID
2024-10-28 17:48:21,857 - root - INFO -    0.7 seconds: C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper
2024-10-28 17:48:21,858 - root - INFO -    0.7 seconds: C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\rembg-comfyui-node
2024-10-28 17:48:21,858 - root - INFO -    0.8 seconds: C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node
2024-10-28 17:48:21,858 - root - INFO -    1.0 seconds: C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui
2024-10-28 17:48:21,858 - root - INFO -    1.1 seconds: C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet
2024-10-28 17:48:21,859 - root - INFO -    1.1 seconds: C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture
2024-10-28 17:48:21,859 - root - INFO - 
2024-10-28 17:48:21,870 - root - INFO - Starting server

2024-10-28 17:48:21,870 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-10-28 17:48:22,697 - root - ERROR - [ERROR] An error occurred while retrieving information for the 'IF_ChatPrompt' node.
2024-10-28 17:48:22,705 - root - ERROR - Traceback (most recent call last):
  File "C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\server.py", line 564, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\server.py", line 531, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 110, in INPUT_TYPES
    node = cls()
           ^^^^^
  File "C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 55, in __init__
    self.stop_strings = self.load_presets(self.stop_file)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 71, in load_presets
    with open(file_path, 'r') as f:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\poldo\\AI\\ComfyUI_windows_portable\\ComfyUI\\input\\IF_AI\\presets\\stop_strings.json'

2024-10-28 18:06:06,327 - root - INFO - got prompt
2024-10-28 18:06:06,425 - root - ERROR - !!! Exception during processing !!! PytorchStreamReader failed locating file constants.pkl: file not found
2024-10-28 18:06:06,426 - root - ERROR - Traceback (most recent call last):
  File "C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture\modules\inpaint\lama\__init__.py", line 75, in lama_inpaint
    model = load_model()
            ^^^^^^^^^^^^
  File "C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture\modules\inpaint\lama\__init__.py", line 43, in load_model
    lama = torch.jit.load(files[0], map_location="cpu")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\poldo\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\jit\_serialization.py", line 163, in load
    cpp_module = torch._C.import_ir_module(cu, os.fspath(f), map_location, _extra_files, _restore_shapes)  # type: ignore[call-arg]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: PytorchStreamReader failed locating file constants.pkl: file not found

2024-10-28 18:06:06,428 - root - INFO - Prompt executed in 0.09 seconds
2024-10-28 18:10:30,373 - root - INFO - got prompt
2024-10-28 18:10:30,399 - root - ERROR - !!! Exception during processing !!! PytorchStreamReader failed locating file constants.pkl: file not found
2024-10-28 18:10:30,401 - root - ERROR - Traceback (most recent call last):
  File "C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture\modules\inpaint\lama\__init__.py", line 75, in lama_inpaint
    model = load_model()
            ^^^^^^^^^^^^
  File "C:\Users\poldo\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture\modules\inpaint\lama\__init__.py", line 43, in load_model
    lama = torch.jit.load(files[0], map_location="cpu")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\poldo\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\jit\_serialization.py", line 163, in load
    cpp_module = torch._C.import_ir_module(cu, os.fspath(f), map_location, _extra_files, _restore_shapes)  # type: ignore[call-arg]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: PytorchStreamReader failed locating file constants.pkl: file not found

2024-10-28 18:10:30,404 - root - INFO - Prompt executed in 0.02 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
Workflow too large. Please manually upload the workflow from local file system.
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

**Comment by jqy-yo** [comment]
I encountered the same problem

**Comment by tungnguyensipher** [comment]
Should be fixed in the latest update (node will download and replace the old incompatible model file).
