### ISSUE TITLE
comfyui-art-venture module for custom nodes: cannot import name 'ImpImporter' from 'pkgutil' 

### ISSUE THREAD

**Issue by xingzhaoyang** [sipherxyz/comfyui-art-venture#59]
Adding F:\ComfyUI_windows_portable\ComfyUI\custom_nodes to sys.path
Traceback (most recent call last):
  File "F:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2024, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture\__init__.py", line 13, in <module>
    from .modules.nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture\modules\nodes.py", line 12, in <module>
    from .utility_nodes import (
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture\modules\utility_nodes.py", line 17, in <module>
    from .utils import pil2tensor, tensor2pil, ensure_package, get_dict_attribute
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture\modules\utils.py", line 9, in <module>
    import pkg_resources
  File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pkg_resources\__init__.py", line 43, in <module>
    from pkgutil import ImpImporter
ImportError: cannot import name 'ImpImporter' from 'pkgutil' (F:\ComfyUI_windows_portable\python_embeded\python312.zip\pkgutil.pyc). Did you mean: 'zipimporter'?

Cannot import F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture module for custom nodes: cannot import name 'ImpImporter' from 'pkgutil'

**Comment by Arshitecture** [comment]
I have the same problem here; even I tried to update my Pip and Python.

**Comment by xingzhaoyang** [comment]
> I have the same problem here; even I tried to update my Pip and Python.

Problem solved?

**Comment by Arshitecture** [comment]
Yes, I just updated my pip for Python 3.12 ( and you need to update the pip for embedded Python). 

check this: https://stackoverflow.com/questions/77364550/attributeerror-module-pkgutil-has-no-attribute-impimporter-did-you-mean

**Comment by algion** [comment]
The update did not solve the problem, and then I had to replace two lines in the file F:\ComfyUI_windows\venv\Lib\site-packages\pkg_resources\__init__.py (the virtual environment venv was used). Instead of the commented line, I inserted the following two:
##register_finder(pkgutil.ImpImporter, find_on_path)##
from importlib.machinery import PathFinder
register_finder(PathFinder, find_on_path)
And further in the text - the second replacement:
##register_namespace_handler(pkgutil.ImpImporter, file_ns_handler)##
register_namespace_handler(importlib.machinery.PathFinder, file_ns_handler)
